```yaml
name: FreeRDP

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup RDP
      uses: iyanmv/setup-nx-ubuntu@v0.1.0
      with:
        ssh-keys: ${{ secrets.SSHKEY }}

    - name: Build
      run: |
        sudo apt update
        sudo apt install xfce4 xfce4-goodies -y
        sudo apt install firefox -y

        echo -e "password\npassword" | sudo passwd ubuntu
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo service sshd restart

    - name: Show RDP Information
      run: |
        ifconfig
```
